#https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-eureka.yml

global:
  scrape_interval: 10s

scrape_configs:

  - job_name: discovery-server
    eureka_sd_configs:
      - server: http://discovery:8761/eureka
      #- server: http://host.docker.internal:8761/eureka
      #- server: http://localhost:8761/eureka
    relabel_configs:
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_scrape ]
        action: keep
        regex: true
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_path ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [ __address__, __meta_eureka_app_instance_metadata_prometheus_port ]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

  - job_name: config-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'config:8888' ]

  - job_name: sso-server
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'sso:80' ]
