server:
  port: 8761

eureka:
  instance:
    hostName: ${spring.application.name}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
