server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
spring.security.oauth2.client.provider.keycloak.issuer-uri: http://localhost/realms/BookLibrary

logging:
  level:
    #ROOT: DEBUG
    reactor:
      netty: INFO
    org:
      springframework: INFO
