apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /discovery/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: discovery
                port:
                  number: 8761
          - path: /(eureka/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: discovery
                port:
                  number: 8761
