server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          #search-locations: file:/var/config
          search-locations: classpath:/config
        git:
          uri: https://localhost/config-server-repo.git
          clone-on-start: true
          username: test
          password: test
          default-label: master
          skip-ssl-validation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
