apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:14.7-alpine
          name: db
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db
